-- MySQL Script generated by MySQL Workbench
-- 05/01/16 11:25:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`daysOfWeek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`daysOfWeek` (
  `idOfWeek` INT NOT NULL AUTO_INCREMENT,
  `dayOfWeekName` VARCHAR(45) NOT NULL,
  `dayOfWeekShortName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOfWeek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profiles` (
  `idOfProfile` INT NOT NULL AUTO_INCREMENT,
  `profileName` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idOfProfile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departments` (
  `idOfDepartment` INT NOT NULL AUTO_INCREMENT,
  `departmentName` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idOfDepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `idGroup` INT NOT NULL AUTO_INCREMENT,
  `groupParentId` INT NOT NULL,
  `groupName` VARCHAR(120) NOT NULL,
  `groupSemester` INT(1) NOT NULL,
  `groupProfileId` INT NOT NULL,
  `groupDepartmentId` INT NOT NULL,
  PRIMARY KEY (`idGroup`, `groupDepartmentId`, `groupProfileId`),
  INDEX `fk_groups_profiles1_idx` (`groupProfileId` ASC),
  INDEX `fk_groups_departments1_idx` (`groupDepartmentId` ASC),
  CONSTRAINT `fk_groups_profiles1`
    FOREIGN KEY (`groupProfileId`)
    REFERENCES `mydb`.`profiles` (`idOfProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_departments1`
    FOREIGN KEY (`groupDepartmentId`)
    REFERENCES `mydb`.`departments` (`idOfDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers` (
  `idOfTeacher` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(250) NOT NULL,
  `departmentId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOfTeacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lectureLeaders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lectureLeaders` (
  `idLectureLeaders` INT NOT NULL AUTO_INCREMENT,
  `teacherId` INT NOT NULL,
  PRIMARY KEY (`idLectureLeaders`, `teacherId`),
  INDEX `fk_lectureLeaders_teachers1_idx` (`teacherId` ASC),
  CONSTRAINT `fk_lectureLeaders_teachers1`
    FOREIGN KEY (`teacherId`)
    REFERENCES `mydb`.`teachers` (`idOfTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lectureTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lectureTypes` (
  `idOfLectureType` INT NOT NULL AUTO_INCREMENT,
  `lectureName` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idOfLectureType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lectureFrequenceParity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lectureFrequenceParity` (
  `idOfParity` INT NOT NULL,
  `nameOfParity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOfParity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `idOfRoom` INT NOT NULL,
  `roomName` VARCHAR(45) NOT NULL,
  `roomNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOfRoom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lectureRooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lectureRooms` (
  `idOfRooms` INT NOT NULL AUTO_INCREMENT,
  `roomId` INT NOT NULL,
  PRIMARY KEY (`idOfRooms`, `roomId`),
  INDEX `fk_lectureRooms_room1_idx` (`roomId` ASC),
  CONSTRAINT `fk_lectureRooms_room1`
    FOREIGN KEY (`roomId`)
    REFERENCES `mydb`.`room` (`idOfRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lectures` (
  `idOfLectures` INT NOT NULL AUTO_INCREMENT,
  `lectureLeadersId` INT NOT NULL,
  `lectureDayOfWeekId` INT NOT NULL,
  `lectureName` VARCHAR(120) NOT NULL,
  `lectureTypeId` INT NOT NULL,
  `lectureGroupId` INT NOT NULL,
  `lectureFrequence` INT NOT NULL,
  `lecutreFrequenceParityId` INT NOT NULL,
  `lectureRoomsId` INT NOT NULL,
  `lectureTimeStart` TIME NOT NULL,
  `lectureTimeStop` TIME NOT NULL,
  `lectureAnnotiation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOfLectures`, `lectureDayOfWeekId`, `lectureGroupId`, `lectureLeadersId`, `lectureTypeId`, `lecutreFrequenceParityId`, `lectureRoomsId`),
  INDEX `fk_lectures_lectureLeaders_idx` (`lectureLeadersId` ASC),
  INDEX `fk_lectures_daysOfWeek1_idx` (`lectureDayOfWeekId` ASC),
  INDEX `fk_lectures_lectureTypes1_idx` (`lectureTypeId` ASC),
  INDEX `fk_lectures_groups1_idx` (`lectureGroupId` ASC),
  INDEX `fk_lectures_lectureFrequenceParity1_idx` (`lecutreFrequenceParityId` ASC),
  INDEX `fk_lectures_lectureRooms1_idx` (`lectureRoomsId` ASC),
  CONSTRAINT `fk_lectures_lectureLeaders`
    FOREIGN KEY (`lectureLeadersId`)
    REFERENCES `mydb`.`lectureLeaders` (`idLectureLeaders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lectures_daysOfWeek1`
    FOREIGN KEY (`lectureDayOfWeekId`)
    REFERENCES `mydb`.`daysOfWeek` (`idOfWeek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lectures_lectureTypes1`
    FOREIGN KEY (`lectureTypeId`)
    REFERENCES `mydb`.`lectureTypes` (`idOfLectureType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lectures_groups1`
    FOREIGN KEY (`lectureGroupId`)
    REFERENCES `mydb`.`groups` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lectures_lectureFrequenceParity1`
    FOREIGN KEY (`lecutreFrequenceParityId`)
    REFERENCES `mydb`.`lectureFrequenceParity` (`idOfParity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lectures_lectureRooms1`
    FOREIGN KEY (`lectureRoomsId`)
    REFERENCES `mydb`.`lectureRooms` (`idOfRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacherWorkingPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teacherWorkingPlan` (
  `teacherId` INT NOT NULL,
  `dayOfWeekId` INT NOT NULL,
  `timeStart` TIME NOT NULL,
  `timeStop` TIME NOT NULL,
  PRIMARY KEY (`teacherId`, `dayOfWeekId`),
  INDEX `fk_teacherWorkingPlan_daysOfWeek1_idx` (`dayOfWeekId` ASC),
  CONSTRAINT `fk_teacherWorkingPlan_daysOfWeek1`
    FOREIGN KEY (`dayOfWeekId`)
    REFERENCES `mydb`.`daysOfWeek` (`idOfWeek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacherWorkingPlan_teachers1`
    FOREIGN KEY (`teacherId`)
    REFERENCES `mydb`.`teachers` (`idOfTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
