# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daysofweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweekname', models.CharField(db_column='dayOfWeekName', max_length=45)),
                ('dayofweekshortname', models.CharField(db_column='dayOfWeekShortName', max_length=45)),
            ],
            options={
                'db_table': 'daysOfWeek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(db_column='departmentName', max_length=120)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupparentid', models.IntegerField(db_column='groupParentId')),
                ('groupname', models.CharField(db_column='groupName', max_length=120)),
                ('groupsemester', models.IntegerField(db_column='groupSemester')),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturefrequenceparity',
            fields=[
                ('idofparity', models.IntegerField(db_column='idOfParity', primary_key=True, serialize=False)),
                ('nameofparity', models.CharField(db_column='nameOfParity', max_length=45)),
            ],
            options={
                'db_table': 'lectureFrequenceParity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturename', models.CharField(db_column='lectureName', max_length=120)),
                ('lecturefrequence', models.IntegerField(db_column='lectureFrequence')),
                ('lecturetimestart', models.TimeField(db_column='lectureTimeStart')),
                ('lecturetimestop', models.TimeField(db_column='lectureTimeStop')),
                ('lectureannotiation', models.CharField(db_column='lectureAnnotiation', max_length=45)),
            ],
            options={
                'db_table': 'lectures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturetypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturename', models.CharField(db_column='lectureName', max_length=120)),
            ],
            options={
                'db_table': 'lectureTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('idofroom', models.IntegerField(db_column='idOfRoom', primary_key=True, serialize=False)),
                ('roomname', models.CharField(db_column='roomName', max_length=45)),
                ('roomnumber', models.CharField(db_column='roomNumber', max_length=45)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=250)),
                ('departmentid', models.CharField(db_column='departmentId', max_length=45)),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacherworkingplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.TimeField(db_column='timeStart')),
                ('timestop', models.TimeField(db_column='timeStop')),
            ],
            options={
                'db_table': 'teacherWorkingPlan',
                'managed': False,
            },
        ),
    ]
